# Generated by Django 6.0.1 on 2026-02-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0002_scheduleentry_teacher_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleresult",
            name="combined_class_assignments",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='格式: {"分组名": ["教师名1", "教师名2", ...]}',
                verbose_name="校本课程分组分配",
            ),
        ),
    ]
