# Generated by Django 6.0.6 on 2026-07-01 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_school_classsubjectteacher_school_and_more"),
        ("scheduler", "0005_scheduleresult_is_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleresult",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_results",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
    ]
