# Generated by Django 6.0.6 on 2026-07-01 08:13

from django.db import migrations


def populate_school(apps, schema_editor):
    """将 scheduler 模型的数据关联到默认学校。"""
    School = apps.get_model('core', 'School')
    ScheduleResult = apps.get_model('scheduler', 'ScheduleResult')

    default_school = School.objects.first()
    if default_school:
        ScheduleResult.objects.all().update(school=default_school)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0006_scheduleresult_school"),
        ("core", "0030_create_default_school"),
    ]

    operations = [
        migrations.RunPython(populate_school, noop),
    ]
