# Generated by Django 6.0.1 on 2026-01-30 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CombinedClassGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分组名称")),
            ],
            options={
                "verbose_name": "合班课分组",
                "verbose_name_plural": "合班课分组",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="场地名称")),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "普通教室"),
                            ("PLAYGROUND", "操场"),
                            ("LAB", "实验室"),
                            ("HOME_EC", "家政室"),
                        ],
                        max_length=20,
                        verbose_name="场地类型",
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(default=1, verbose_name="同时容纳班数"),
                ),
            ],
            options={
                "verbose_name": "场地",
                "verbose_name_plural": "场地",
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="班级名称")),
                ("grade", models.IntegerField(default=1, verbose_name="年级")),
            ],
            options={
                "verbose_name": "班级",
                "verbose_name_plural": "班级",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="课程名称")),
                (
                    "weekly_hours",
                    models.IntegerField(default=1, verbose_name="周课时数"),
                ),
                (
                    "is_am_preferred",
                    models.BooleanField(default=False, verbose_name="上午优先"),
                ),
                (
                    "allow_consecutive",
                    models.BooleanField(default=False, verbose_name="允许连堂"),
                ),
                (
                    "max_daily_limit",
                    models.IntegerField(default=1, verbose_name="单日上限"),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "普通教室"),
                            ("PLAYGROUND", "操场"),
                            ("LAB", "实验室"),
                            ("HOME_EC", "家政室"),
                        ],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="场地类型",
                    ),
                ),
                (
                    "is_combined_class",
                    models.BooleanField(default=False, verbose_name="合班课"),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
            },
        ),
        migrations.CreateModel(
            name="TravelGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分组名称")),
                (
                    "day_off",
                    models.IntegerField(
                        choices=[
                            (0, "周一"),
                            (1, "周二"),
                            (2, "周三"),
                            (3, "周四"),
                            (4, "周五"),
                        ],
                        verbose_name="禁排日",
                    ),
                ),
            ],
            options={
                "verbose_name": "送教分组",
                "verbose_name_plural": "送教分组",
            },
        ),
        migrations.CreateModel(
            name="CombinedClassSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="class_sets",
                        to="core.combinedclassgroup",
                        verbose_name="合班分组",
                    ),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        related_name="combined_sets",
                        to="core.schoolclass",
                        verbose_name="班级",
                    ),
                ),
            ],
            options={
                "verbose_name": "合班课集合",
                "verbose_name_plural": "合班课集合",
            },
        ),
        migrations.AddField(
            model_name="combinedclassgroup",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.subject",
                verbose_name="合班课程",
            ),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "combined_class_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.combinedclassgroup",
                        verbose_name="合班课分组",
                    ),
                ),
                (
                    "travel_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.travelgroup",
                        verbose_name="送教分组",
                    ),
                ),
            ],
            options={
                "verbose_name": "教师",
                "verbose_name_plural": "教师",
            },
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="homeroom_teacher",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homeroom_class",
                to="core.teacher",
                verbose_name="班主任",
            ),
        ),
        migrations.CreateModel(
            name="ClassSubjectTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_assignments",
                        to="core.schoolclass",
                        verbose_name="班级",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.subject",
                        verbose_name="课程",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.teacher",
                        verbose_name="教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "授课分配",
                "verbose_name_plural": "授课分配",
                "unique_together": {("school_class", "subject")},
            },
        ),
    ]
