# Generated by Django 6.0.1 on 2026-02-08 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_restore_combined_class_with_exclude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulersettings",
            name="h9_consecutive_forbidden",
            field=models.CharField(
                default="1,2;3,4",
                help_text='禁止连堂跨越的节次对，格式如"1,2;3,4"表示第2-3节和第4-5节之间不能连堂（0起始）',
                max_length=50,
                verbose_name="连堂禁跨节次对",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="combined_class_group",
            field=models.ForeignKey(
                blank=True,
                help_text="手动指定该教师属于哪个校本课程组，留空则自动分配",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.combinedclassgroup",
                verbose_name="校本课程分组",
            ),
        ),
    ]
