# Generated by Django 6.0.1 on 2026-06-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_schedulersettings_h14_homeroom_main_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulersettings",
            name="h15_teacher_max_main_subjects",
            field=models.IntegerField(
                default=1,
                help_text='同一教师最多可担任几门不同的主课科目（默认1）。教同一门主课的多个班级不计入此上限，由课程的"单师最多班数"单独控制',
                verbose_name="单师最多主课数",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="is_main_subject",
            field=models.BooleanField(
                default=False,
                help_text='主课(如语文数学英语)，单个教师可担任的主课门数由排课设置中的"单师最多主课数"控制',
                verbose_name="主课",
            ),
        ),
    ]
