# Generated by Django 6.0.6 on 2026-07-01 08:12

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_reorder_travel_groups_by_day_off"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "import_key",
                    models.CharField(
                        db_index=True,
                        default=core.models.generate_import_key,
                        editable=False,
                        help_text="系统生成的稳定导入键，用于导入导出时精确关联。",
                        max_length=32,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="导入键格式无效。", regex="^[0-9a-f]{32}$"
                            )
                        ],
                        verbose_name="导入键",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="学校名称")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="简称"
                    ),
                ),
            ],
            options={
                "verbose_name": "学校",
                "verbose_name_plural": "学校",
            },
        ),
        migrations.AddField(
            model_name="classsubjectteacher",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_assignments",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AddField(
            model_name="combinedclassgroup",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="combined_class_groups",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AddField(
            model_name="schedulelock",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_locks",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="school",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduler_settings",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AddField(
            model_name="teacherblockedtime",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_blocked_times",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AddField(
            model_name="teacherqualification",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_qualifications",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AddField(
            model_name="travelgroup",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travel_groups",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="combinedclassgroup",
            unique_together={("school", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("school", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="schoolclass",
            unique_together={("school", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("school", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="teacher",
            unique_together={("school", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="travelgroup",
            unique_together={("school", "name")},
        ),
    ]
