# Generated by Django 6.0.6 on 2026-07-01 08:13

import uuid

from django.db import migrations


def create_default_school(apps, schema_editor):
    """创建默认学校并将所有现有数据关联到它。"""
    School = apps.get_model('core', 'School')

    default_school = School.objects.create(
        name='默认学校',
        short_name='默认',
        import_key=uuid.uuid4().hex,
    )

    models_with_school = [
        'TravelGroup',
        'TeacherBlockedTime',
        'Subject',
        'CombinedClassGroup',
        'Teacher',
        'SchoolClass',
        'Location',
        'TeacherQualification',
        'ClassSubjectTeacher',
        'ScheduleLock',
        'SchedulerSettings',
    ]

    for model_name in models_with_school:
        Model = apps.get_model('core', model_name)
        Model.objects.all().update(school=default_school)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_school_classsubjectteacher_school_and_more"),
    ]

    operations = [
        migrations.RunPython(create_default_school, noop),
    ]
