# Generated by Django 6.0.6 on 2026-07-01 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_create_default_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classsubjectteacher",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_assignments",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AlterField(
            model_name="combinedclassgroup",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="combined_class_groups",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AlterField(
            model_name="schedulelock",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_locks",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AlterField(
            model_name="schedulersettings",
            name="school",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduler_settings",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AlterField(
            model_name="schoolclass",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AlterField(
            model_name="teacherblockedtime",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_blocked_times",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AlterField(
            model_name="teacherqualification",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_qualifications",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
        migrations.AlterField(
            model_name="travelgroup",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travel_groups",
                to="core.school",
                verbose_name="所属学校",
            ),
        ),
    ]
