# Generated by Django 6.0.6 on 2026-07-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_classsubjectteacher_school_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulersettings",
            name="am_period_count",
            field=models.IntegerField(
                default=4,
                help_text="前几节算上午。默认4表示节次0-3为上午、4及以后为下午。",
                verbose_name="上午节数",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="class_meeting_slot",
            field=models.CharField(
                default="4,3",
                help_text='班会固定在哪个时段，格式"星期,节次"从0开始。如"4,3"表示周五第4节。留空表示没有固定班会。',
                max_length=20,
                verbose_name="班会时段",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="day_labels",
            field=models.JSONField(
                default=list,
                help_text='每天的显示名称，JSON数组如["周一","周二","周三","周四","周五"]',
                verbose_name="每日标签",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="periods_per_day",
            field=models.JSONField(
                default=dict,
                help_text='每天几节课，JSON如{"0":6,"1":6,"2":6,"3":6,"4":4}，键为星期索引0起始',
                verbose_name="每天节数",
            ),
        ),
        migrations.AlterField(
            model_name="schedulelock",
            name="day",
            field=models.IntegerField(
                choices=[
                    (0, "周一"),
                    (1, "周二"),
                    (2, "周三"),
                    (3, "周四"),
                    (4, "周五"),
                    (5, "周六"),
                    (6, "周日"),
                ],
                verbose_name="星期",
            ),
        ),
        migrations.AlterField(
            model_name="teacherblockedtime",
            name="day",
            field=models.IntegerField(
                choices=[
                    (0, "周一"),
                    (1, "周二"),
                    (2, "周三"),
                    (3, "周四"),
                    (4, "周五"),
                    (5, "周六"),
                    (6, "周日"),
                ],
                verbose_name="星期",
            ),
        ),
        migrations.AlterField(
            model_name="travelgroup",
            name="day_off",
            field=models.IntegerField(
                choices=[
                    (0, "周一"),
                    (1, "周二"),
                    (2, "周三"),
                    (3, "周四"),
                    (4, "周五"),
                    (5, "周六"),
                    (6, "周日"),
                ],
                verbose_name="禁排日",
            ),
        ),
    ]
